name: docs
channels:
  - conda-forge
dependencies:
  - doxygen
  - exhale
  - pydata-sphinx-theme
  - python=3.13
  - sphinx
  - sphinx-copybutton
  - myst-parser
  - breathe
  - standard-imghdr
  - fftw
  - numpy
  - scipy
  - matplotlib
  - meson
  - pkg-config
  - ninja
