name: docs
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - accessible-pygments=0.0.5=pyhd8ed1ab_1
  - alabaster=0.7.16=pyhd8ed1ab_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.2.0=py313hf42fe89_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - black=25.12.0=pyh866005b_0
  - breathe=4.35.0=pyhd8ed1ab_4
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.2.0=py313hde1f3bb_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py313ha61f8ec_3
  - cycler=0.12.1=pyhcf101f3_2
  - docutils=0.17.1=py313h8f79df9_7
  - doxygen=1.13.2=h493aca8_0
  - exhale=0.3.7=pyhd8ed1ab_1
  - fonttools=4.61.1=pyh7db6752_0
  - freetype=2.14.1=hce30654_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - isort=7.0.0=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - kiwisolver=1.4.9=py313h7add70c_2
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcxx=21.1.8=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=haf25636_0
  - libfabric=2.4.0=hce30654_0
  - libfabric1=2.4.0=hc919400_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libhwloc=2.12.1=default_ha3cc4f2_1003
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpmix=5.0.8=h3e7ebac_2
  - libpng=1.6.53=hfab5511_0
  - libsqlite=3.51.1=h9a5124b_0
  - libtiff=4.7.1=h4030677_1
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libxslt=1.1.43=hb2570ba_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - lxml=6.0.2=py313he6cafaa_2
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib=3.10.8=py313h39782a4_0
  - matplotlib-base=3.10.8=py313h58042b9_0
  - mpi=1.0.1=openmpi
  - munkres=1.1.4=pyhd8ed1ab_1
  - mypy_extensions=1.1.0=pyha770c72_0
  - ncurses=6.5=h5e97a16_3
  - nodeenv=1.9.1=pyhd8ed1ab_1
  - nodejs=25.2.1=h5230ea7_1
  - numpy=2.3.5=py313h9771d21_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openmpi=5.0.8=h13a75e3_109
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pillow=12.0.0=py313ha86496b_2
  - pip=25.3=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pydata-sphinx-theme=0.13.3=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyright=1.1.407=py313h9734d34_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.11=hfc2f54d_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.13=8_cp313
  - pytokens=0.3.0=pyhcf101f3_0
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - readline=8.3=h46df422_0
  - requests=2.32.5=pyhd8ed1ab_0
  - roman-numerals=4.1.0=pyhd8ed1ab_0
  - scipy=1.16.3=py313h0d10b07_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - soupsieve=2.8=pyhd8ed1ab_0
  - sphinx=4.5.0=pyh6c4a22f_0
  - sphinxcontrib-applehelp=1.0.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.1=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - standard-imghdr=3.13.0=pyh29332c3_0
  - tk=8.6.13=h892fb3f_3
  - tornado=6.5.4=py313h6535dbc_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - unicodedata2=17.0.0=py313h6535dbc_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.2=h248ca61_0
  - zstd=1.5.7=hbf9d68e_6
